### ISSUE TITLE
How to run ifttt-api-example

### ISSUE THREAD

**Issue by nishantdande** [IFTTT/ifttt-api-example#1]
Hi,
I have downloaded and resolve dependencies but unable to run server with below command - 

>> ruby app.rb 

Am I doing something wrong.

**Comment by kevinebaugh** [comment]
Hello! Go ahead and [reach out directly via the platform](https://platform.ifttt.com/) and we'll be able to take a closer look.

**Comment by nishantdande** [comment]
I didn't understand. Would you please help me in running this code and deploy it to my localhost
