### ISSUE TITLE
Issue with hello world example

### ISSUE THREAD

**Issue by Oxbowl** [IFTTT/ifttt-api-example#3]
I just follow the step by step at https://platform.ifttt.com/docs/hello_world, but after executing the command ruby hello_world.rb, i got this errors, so what is the happening:

$ ruby hello_world.rb
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/railtie.rb:39:in `rescue in block in <class:Railtie>': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/railtie.rb:36:in `block in <class:Railtie>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
        from hello_world.rb:117:in `<main>'

**Comment by kevinebaugh** [comment]
Hi @Oxbowl, this repo is an example of how to [embed Applets via the IFTTT API](https://platform.ifttt.com/docs/embedding_applets). For general IFTTT Platform help, reach out [via the Platform directly](https://platform.ifttt.com). Thanks!
